### PR TITLE
First App Version (Dev Environment)

### PR DESCRIPTION
**Pull request by phrb**
I'm making a pull request, so that everybody can catch up and review what we've done.

What we have so far:
- Build Script
- Rails "Hello World" 
- Readme

Questions:
- Can everyone install and run the app? 
- Can we consider the dev environment ready?
- What about continuous integration? (what about [this](http://docs.travis-ci.com/user/languages/ruby/)?)
- Can we start writing code?

Please, post questions and comments below, let's review what we've done and start coding! :)

### CODE REVIEW

**Comment by renatocf** [comment]
I deleted all my previously cloned repositories and made a fresh clone. Then I switched to branch `dev` and followed the instructions in `README.md`. When I ran `build.sh`, I got the following error:

``` bash
$ ./build.sh
Starting build_db_1...
Cannot start container 1c3cffded65007e6a7f1a95905ca8e6a4cf75b7329987e0ef37b35761fa90971:  (exit status 1)
```

Does this error came from some outdated Docker container? Or did we upload some local file that may have changed the behavior of my Docker?

**Comment by phrb** [comment]
Try stopping and removing all containers:

```
sudo docker stop $(sudo docker ps -a -q)
sudo docker rm $(sudo docker ps -a -q)
```

(found [here](https://coderwall.com/p/ewk0mq/stop-remove-all-docker-containers))

This could also be related to other images in your system. I ran the script without any previous docker image installed. It takes a lot longer, but if you wanna try it, the following removes all images (can't undo!).

```
sudo docker rmi $(sudo docker images -q)
```

(found [here](http://techoverflow.net/blog/2013/10/22/docker-remove-all-images-and-containers/))

**Comment by phrb** [comment]
I stopped and removed all docker containers in my machine, and deleted all images. I was able to build and run the app, here's the [build output](https://gist.github.com/phrb/76e4353bc891b6fa1e64#file-build_output-txt) and the [docker-compose output](https://gist.github.com/phrb/12991c523ff964ea6b08#file-docker_compose_output-txt).

**Comment by renatocf** [comment]
Well, for some unknown reason I turned my computer on this morning and just ran `docker-compose up`. And it magically worked! I believe it was some type of cache that has gone away when I turned off... Conclusion: everything is working fine for me now! If everyone agrees, you can merge it.

**Comment by phrb** [comment]
I think it was the older docker image that you had installed from previous builds. If you didn't run the script again, then docker used an old image.

**Pull request merged**
